### ISSUE TITLE
管理员运行提示：Windows找不到文件

### ISSUE THREAD

**Issue by xiaoan425** [windywater/LDDec#1]
请问下是怎么运行的呢？

**Comment by windywater** [comment]
假如 D:\test.cpp 为加密文件，运行：
`dec.exe D:\test.cpp`
即可

**Comment by xiaoan425** [comment]
谢谢回复，已解决

需要搬梯子下载，直接运行dec.exe闪退，cmd运行可以



从 Windows 版邮件发送

发件人: windywater
发送时间: 2022年12月23日 17:21
收件人: windywater/LDDec
抄送: xiaoan425; Author
主题: Re: [windywater/LDDec] 管理员运行提示：Windows找不到文件 (Issue #1)

假如 D:\test.cpp 为加密文件，运行：
dec.exe D:\test.cpp
即可

**Comment by xiaoan425** [comment]
git找不到了，全网唯一，确实专业
再请问下，这样解密会在服务器留下日志或记录吗？
















在 2022-12-23 17:20:57，"windywater" ***@***.***> 写道：

假如 D:\test.cpp 为加密文件，运行：
dec.exe D:\test.cpp
即可

**Comment by windywater** [comment]
> git找不到了，全网唯一，确实专业 再请问下，这样解密会在服务器留下日志或记录吗？ 在 2022-12-23 17:20:57，"windywater" ***@***.***> 写道： 假如 D:\test.cpp 为加密文件，运行： dec.exe D:\test.cpp 即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

不会

**Comment by windywater** [comment]
close the issue
