### ISSUE TITLE
关于您的项目中主目录里的dec.exe和debug下的dec.exe的区别

### ISSUE THREAD

**Issue by ppoopppopo** [windywater/LDDec#3]
windec可以解密成功。但是，另一个项目我看了一下dec是服务端模型，faker是客户端模型，因为dec主cpp里面有创建faker进程，所以不用手动运行faker，虽然控制台显示文件解密成功，但是实际上文件并没有解密，请问这是为什么？

**Comment by windywater** [comment]
> windec可以解密成功。但是，另一个项目我看了一下dec是服务端模型，faker是客户端模型，因为dec主cpp里面有创建faker进程，所以不用手动运行faker，虽然控制台显示文件解密成功，但是实际上文件并没有解密，请问这是为什么？

windec用在windows上，利用type绕过。另一个工程主要用在linux下，因为我测试cat无法利用，所以用本地tcp通信绕过，windows我本机测试也可用。你需要把Faker.exe重命为notepad.exe，和config.json里保持一致。

**Comment by ppoopppopo** [comment]
好的谢谢博主
