### ISSUE TITLE
是不可以用了吗？，执行过后文件没有解密，window11系统？

### ISSUE THREAD

**Issue by ChenErik** [windywater/LDDec#4]
![image](https://github.com/windywater/LDDec/assets/37365363/b4be5ab5-cc3f-4aa1-af82-03a32e1d6aa3)

**Comment by windywater** [comment]
没有在win11上测试过，win10下可以解密，绿盾版本和你基本一致

**Comment by windywater** [comment]
> @windywater 我是最近win10转win11，win10成功解密文件，自从换成win11执行dec.exe文件无法解密文件

没有测试过win11，你可以在cmd里使用type命令将加密文件回显到另一个文件，如type enc.txt > dec.txt，然后看看这个dec.txt是否已解密。如果仍未解密，就编译Dec/Faker工程（基于Qt），使用本地TCP传输的方式来解密。

**Comment by kejianlin** [comment]
@windywater  win11可以解密成功，但是被公司网管在后台发现我非法解密，我解密目的只是为了工作便利高效。目前在接受公司审查。

**Comment by windywater** [comment]
> @windywater win11可以解密成功，但是被公司网管在后台发现我非法解密，我解密目的只是为了工作便利高效。目前在接受公司审查。

后台是怎么做到发现非法解密的？还是祝你好运吧
