### ISSUE TITLE
如何运行？

### ISSUE THREAD

**Issue by fu7n** [windywater/LDDec#5]
如何运行？
双击dec.exe，闪烁了一下就没了。

**Comment by windywater** [comment]
> 如何运行？ 双击dec.exe，闪烁了一下就没了。

dec.exe <file>
后面跟加密文件路径

**Comment by fu7n** [comment]
已经测试好多次了，解密不了。是不是最新版本不支持呢。7.0.2的
会出现一个   .pptx_dec的文件，然后就自动消失了。
源文件也没被解密。

**Comment by windywater** [comment]
> 已经测试好多次了，解密不了。是不是最新版本不支持呢。7.0.2的 会出现一个 .pptx_dec的文件，然后就自动消失了。 源文件也没被解密。

我们的是6.50版本的。你可以这样试一下，在命令行里：
type 'enc_file' > 'dec_file'
enc_file, dec_file替换为你的文件，然后看这个dec_file是否已被解密
